spring:
  application:
    name: e-library-users

  datasource:
    url: jdbc:postgresql://localhost:5432/${database.name}
    username: ${postgres.user}
    password: ${postgres.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
